---
title: "My First Quarto Presentation"
subtitle: "DS HW2"
author: "<br>Jess Kotlarek"
editor: visual
format: 
    revealjs:
        theme: serif
        highlight-style: tango
        embed-resources: true
        smaller: true
execute: 
  message: false
  warning: false
  echo: true
---

```{r setup, echo = FALSE}
library(tidyverse)
library(corrplot)
library(explore) # mtcars dataset
```

# mtcars

<!--# Really nice that you linked the CRAN page directly...super helpful for anyone who wants to dig deeper into the dataset. One small idea: adding a sentence about what each of the 10 variables measures could help the audience follow along better in the later slides. -->

-   mtcars is the dataset we are using in the homework
    -   It contains fuel consumption and 11 aspects of automobile design and performance for 32 automobiles

::: incremental
```         
    -   mpg: Miles/(US) gallon
    -   cyl: Number of cylinders
    -   disp: Displacement (cu.in.)
    -   hp: Gross horsepower
    -   drat: Rear axle ratio
    -   wt: Weight (1000 lbs)
    -   qsec: 1/4 mile time
    -   vs: Engine (0 = V-shaped, 1 = straight)
    -   am: Transmission (0 = automatic, 1 = manual)
    -   gear: Number of forward gears
    -   carb: Number of carburetors
```
:::

-   It can be found [[*here*]{.underline}](https://cran.r-project.org/web/packages/explore/vignettes/explore-mtcars.html) on CRAN

# mtcars Data

<!--# Showing the code first and then the output is a clean way to walk the audience through what is happening before showing them the full table. The "scroll to see more entries" note is a nice touch too! -->

```{r}
#| eval: false
mtcars
```

::: fragment
```{r}
#| echo: false
mtcars
```

-   scroll to see more entries
:::

# mtcars Table

```{r}
vs_table <- table(mtcars$vs)
names(vs_table) <- c("V-shaped engines", "Straight engines")
```

<!--# I like that you renamed the 0/1 values to actual engine names, makes the table way more readable! -->

::: fragment
```{r}
#| echo: false
vs_table
```
:::

# mtcars Graph

<!--# Great scatterplot! One idea: coloring the points by number of cylinders using color=factor(cyl) inside aes() could add another layer of info without cluttering the plot at all. -->

```{r}
#| eval: false
ggplot(mtcars, aes(x=disp, y=mpg)) +
    geom_point() +
    labs(x = "Disp",
         y = "Miles per Gallon",
         title = "Graph Comparing Disp and Miles per Gallon")
```

::: fragment
```{r}
#| echo: false
ggplot(mtcars, aes(x=disp, y=mpg)) +
    geom_point() +
    labs(x = "Disp",
         y = "Miles per Gallon",
         title = "Graph Comparing Disp and Miles per Gallon")
```
:::

# mtcars Corrplot

```{r}
#| eval: false
mtcars |>
    select(where(is.numeric)) |> 
    cor() |> 
    corrplot(diag = F, type = "lower")
```

::: fragment
```{r}
#| echo: false
mtcars |>
    select(where(is.numeric)) |> 
    cor() |> 
    corrplot(diag = F, type = "lower")
```
:::

# Thank You!

<!--# Nice presentation overall, the use of fragments throughout kept it easy to follow! -->
